### PR TITLE
Add package.json and typings

### PR DESCRIPTION
**Pull request by vthib**
Hello

First, thanks a lot for this project, we use it and are quite happy with it. Would you be ok with publishing it on NPM? I have added the package.json as well as typescript typings in this pull request if it's ok for you.

### CODE REVIEW

**Comment by gregallensworth** [comment]
Nice. Thank you for that. I have merged these two new files.

**Comment by vthib** [comment]
Thanks! Are you going to publish it on npm as well? Or should I do it?

**Comment by gregallensworth** [comment]
Feel free to do it. I am caught up in other work for a while, including updating npm on my machine which is giving me problems...   Thank you for that.  I'm glad you like the control.

**Comment by vthib** [comment]
I have just done so: https://www.npmjs.com/package/leaflet-control-boxzoom
Thanks a lot again!

**Pull request merged**
